import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist, Geist_Mono } from "next/font/google";

import Providers from "@/components/providers";

import "./globals.css";

const font = Bricolage_Grotesque({
    display: "swap",
    preload: true,
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Flare List",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${font.className} overflow-x-hidden antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
