import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import Providers from "@/components/providers";

import "./globals.css";

export const metadata: Metadata = {
    title: "Flare List",
    description: "Generated by create next app",
};

const bricolageGrotesque = Bricolage_Grotesque({
    subsets: ["latin"],
    display: "swap",
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    variable: "--font-primary",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${bricolageGrotesque.variable} font-primary antialiased`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
